- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tempest-integrated-networking
    gate:
      jobs:
        - tempest-integrated-networking
